# Generated by Django 5.1.4 on 2025-01-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaroomconnector',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='mediaroomconnector',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='mediaroomconnector',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.review'),
        ),
        migrations.AlterField(
            model_name='mediaroomconnector',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20),
        ),
    ]
