# Generated by Django 5.1.4 on 2025-01-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mediaroomconnector_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaroomconnector',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='core.product'),
        ),
    ]
