# Generated by Django 5.1.4 on 2025-01-23 06:19

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mediaroomconnector_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaroomconnector',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='mediaroomconnector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/organization/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/user/', verbose_name='Image'),
        ),
    ]
