# Generated by Django 5.1.4 on 2025-01-06 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productcategory_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.UUIDField(auto_created=True, editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
