# Generated by Django 5.1.4 on 2025-01-06 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productcategory_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
