# Generated by Django 5.1.4 on 2025-01-08 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_added_on_alter_order_delivary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 1, 8, 6, 3, 7, 692586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 8, 6, 3, 7, 692586, tzinfo=datetime.timezone.utc)),
        ),
    ]
