# Generated by Django 5.1.4 on 2025-01-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_order_status_review_reviewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_status',
            field=models.CharField(choices=[('reviewed', 'Reviewed'), ('not_reviewed', 'Not Reviewed')], default='not_reviewed', max_length=20),
        ),
    ]
