# Generated by Django 5.1.4 on 2025-01-09 07:09

import autoslug.fields
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/reviews', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='uid', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='core.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(through='core.ProductReview', to='core.product'),
        ),
        migrations.DeleteModel(
            name='ReviewItem',
        ),
    ]
