# Generated by Django 5.1.4 on 2025-01-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review_comment_review_image_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(through='core.ProductReview', to='core.review'),
        ),
    ]
