# Generated by Django 5.1.4 on 2025-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_review_product_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='review_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review_status',
            field=models.CharField(choices=[('reviewed', 'Reviewed'), ('not_reviewed', 'Not Reviewed')], default='not_reviewed', max_length=20),
        ),
    ]
