# Generated by Django 5.1.4 on 2025-01-09 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_order_review_status_orderitem_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
