# Generated by Django 5.1.4 on 2025-01-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_productreview_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivary_date',
            new_name='delivery_date',
        ),
    ]
