# Generated by Django 5.1.4 on 2025-01-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganization',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
