# Generated by Django 5.1.4 on 2025-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_userorganization_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(related_name='review', through='core.ProductReview', to='core.review'),
        ),
    ]
