# Generated by Django 5.1.4 on 2025-01-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_status',
            field=models.CharField(choices=[('reviewed', 'Reviewed'), ('not_reviewed', 'Not Reviewed')], default='not_reviewed', max_length=30),
        ),
    ]
